name: Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: aflpp
            context: .
            file: ./Dockerfile
            tag: fuzzamoto:ci
          - name: libafl
            context: .
            file: ./Dockerfile.libafl
            tag: fuzzamoto-libafl:ci
          - name: coverage
            context: .
            file: ./Dockerfile.coverage
            tag: fuzzamoto-coverage:ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image - ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: false # build only - don't push to registry
          tags: ${{ matrix.tag }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

