name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Install nyx dependencies
      run: sudo apt update && sudo apt install -y libgtk-3-dev pax-utils python3-msgpack python3-jinja2 libcapstone-dev
    - name: Build
      run: cargo build --verbose
    - name: Build for fuzzing
      run: cargo build --verbose --features fuzz
    - name: Build for fuzzing with benchmarking
      run: cargo build --verbose --features fuzz,bench
    - name: Build for reproducing
      run: cargo build --verbose --features reproduce
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting for all crates
      run: cargo fmt --all --check
